#!/usr/bin/python -u
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU Lesser General Public License as published 
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""Manual Xen Certification script"""


import sys
sys.path.append("/opt/xensource/sm")
from datetime import datetime
import time
import commands
import XenCertCommon
import StorageHandler
from XenCertLog import InitLogging, UnInitLogging, PrintToLog, Print, GetLogFileName


version = "@KIT_VERSION@"

def main():
    """Main Routine"""

    pass_all = True
    g_storage_conf = {}
    InitLogging()
    PrintToLog("***********************************************************************\n")

    (options, args) = XenCertCommon.parse_args(version)
    # Convert legacy lvmoXXX storage types to their base type
    if options.storage_type:
        options.storage_type = options.storage_type.lstrip("lvmo")

    if args:
        Print("Unknown arguments found: %s" % args)
        sys.exit(1)

    PrintToLog("The XenCert command executed is: \n\n")
    XenCertCommon.printCommand(sys.argv)
    PrintToLog('\n\n')

    if options.help:
        XenCertCommon.DisplayUsage()
        return 0

    if not XenCertCommon.valid_arguments(options, g_storage_conf):
        return 1

    XenCertCommon.store_configuration(g_storage_conf, options)
    
    # Now is the time to instantiate the right handler based on the
    # requested storage type and hand it over to the handler to
    # perform the certification process
    handler = StorageHandler.GetStorageHandler(g_storage_conf)
    build = commands.getoutput('cat /etc/xensource-inventory | grep BUILD_NUMBER')
    Print("********************** Welcome to XenCert %s %s *****************" % (version, build))
    Print("Test start time: %s" % time.asctime(time.localtime()))
    start = datetime.now()
    Print("***********************************************************************")  
    testAll = False

    if not options.functional and not options.control and not options.multipath and not options.pool and not options.data and not options.metadata:
        testAll = True
    
    if options.multipath or testAll:
        Print("Performing multipath configuration verification.")
        (retValMP, checkPointsMP, totalCheckPointsMP) = handler.MPConfigVerificationTests()
        if checkPointsMP != totalCheckPointsMP:
            pass_all = False
        Print("***********************************************************************")
        timeOfCompletionMP = time.asctime(time.localtime())
    else:
        retValMP = None
        checkPointsMP = 0
        totalCheckPointsMP = 1
        timeOfCompletionMP = 0

    if options.control or testAll: 
        Print("Performing control path stress tests.")
        (retValControl, checkPointsControl, totalCheckPointsControl) = handler.ControlPathStressTests()
        if checkPointsControl != totalCheckPointsControl:
            pass_all = False
        Print("***********************************************************************")
        timeOfCompletionControl = time.asctime(time.localtime())
    else:
        retValControl = None
        checkPointsControl = 0
        totalCheckPointsControl = 1
        timeOfCompletionControl = 0

    if options.pool or testAll:
        Print("Performing pool tests to ensure consistency.")
        (retValPool, checkPointsPool, totalCheckPointsPool) = handler.PoolTests()
        if checkPointsPool != totalCheckPointsPool:
            pass_all = False
        Print("***********************************************************************")
        timeOfCompletionPool = time.asctime(time.localtime())

    if options.functional or testAll: 
        Print("Performing functional tests.")
        (retValFunctional, checkPointsFunctional, totalCheckPointsFunctional) = handler.FunctionalTests()
        if checkPointsFunctional != checkPointsFunctional:
            pass_all = False
        Print("***********************************************************************")
        timeOfCompletionFunctional = time.asctime(time.localtime())

    if options.data or testAll: 
        Print("Performing data IO tests.")
        (retValData, checkPointsData, totalCheckPointsData) = handler.DataIntegrityTests()
        if checkPointsData != checkPointsData:
            pass_all = False
        Print("***********************************************************************")
        timeOfCompletionData = time.asctime(time.localtime())
    
    if options.metadata:
        Print("Performing metadata tests.")
        (retValMetadata, checkPointsMetaData, totalCheckPointsMetaData) = handler.MetaDataTests()
        Print("***********************************************************************")
        timeOfCompletionMetadata = time.asctime(time.localtime())

    # Now display all the results
    if options.multipath or testAll:
        Print("***********************************************************************")
        XenCertCommon.showReport('Multipath configuration verification results', retValMP, checkPointsMP, totalCheckPointsMP,
                   timeOfCompletionMP)

    if options.control or testAll:     	
        Print("***********************************************************************")
        XenCertCommon.showReport('Control path stress test results', retValControl, checkPointsControl, totalCheckPointsControl,
                   timeOfCompletionControl)

    if options.pool or testAll:
        Print("***********************************************************************")
        XenCertCommon.showReport('Pool test results', retValPool, checkPointsPool, totalCheckPointsPool, timeOfCompletionPool)

    if options.functional or testAll:     	
        Print("***********************************************************************")
        XenCertCommon.showReport('Functional test results', retValFunctional, checkPointsFunctional, totalCheckPointsFunctional,
                   timeOfCompletionFunctional)

    if options.data or testAll:         
        Print("***********************************************************************")
        XenCertCommon.showReport('Data test results', retValData, checkPointsData, totalCheckPointsData, timeOfCompletionData)
        
    if options.metadata:
        Print("***********************************************************************")
        XenCertCommon.showReport('Metadata test results', retValMetadata, checkPointsMetaData, totalCheckPointsMetaData, timeOfCompletionMetadata)

    Print("***********************************************************************")
    Print("End of XenCert certification suite.")
    Print("Please find the report for this test run at: %s" % GetLogFileName())
    Print("***********************************************************************")
    end = datetime.now()
    Print("Test end time: %s" % time.asctime(time.localtime()))
    timed = end - start
    hr = timed.seconds/3600
    min = timed.seconds%3600/60
    sec = timed.seconds%60
    if hr > 0:
        Print("Execution time: %d hours, %d minutes, %d seconds." % (hr, min, sec))
    elif min > 0:
        Print("Execution time: %d minutes, %d seconds." % (min, sec))
    elif sec > 0:
        Print("Execution time: %d seconds." % sec)	    
    
    Print("***********************************************************************")  
    UnInitLogging()

    if pass_all:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
